data:
    dataset: 'Coco'
    labels: logs/magicpoint_synth_homoAdapt_coco/predictions
    root: 
    root_split_txt: 

    gaussian_label:
        enable: true
        params:
            GaussianBlur: {sigma: 0.2}

    cache_in_memory: false
    preprocessing:
        resize: [240, 320]
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur']
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3

front_end_model: 'Train_model_heatmap'

training:
    workers_train: 4
    workers_val: 2

model:
    name: 'SuperPointNetMobileNetV2'
    params: {}
    detector_loss:
        loss_type: 'softmax'

    batch_size: 2
    eval_batch_size: 2
    learning_rate: 0.0001
    detection_threshold: 0.015
    lambda_loss: 1
    nms: 4
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4
            lambda_d: 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.2'

retrain: True
reset_iter: True
train_iter: 200000
validation_interval: 200
tensorboard_interval: 200
save_interval: 200
validation_size: 5

pretrained:

wandb:
    enable: true
    project: "superpoint-mobilenet"
    name: "mobilenetv2-coco"
    tags: ["mobilenetv2", "coco", "superpoint"]
    notes: "MobileNetV2 backbone with COCO dataset"
    config:
        model: "SuperPointNetMobileNetV2"
        dataset: "COCO"
        batch_size: 2
        learning_rate: 0.0001
        loss_type: "sparse"
        augmentation: "photometric" 