data:
  name: 'kitti'
  dataset: 'kitti'
  preprocessing:
    resize: [240, 320]
    resize_float: true
  train_iter: 200000
  batch_size: 32
  eval_batch_size: 32
  cache_in_memory: true
  train_split: 'train'
  val_split: 'val'
  subfolders: ['image_0', 'image_1']
  warp_input: true
  homography_adaptation:
    num: 1
    aggregation: 'max'
    valid_border_margin: 3
    homographies:
      translation: true
      rotation: true
      scaling: true
      perspective: true
      scaling_amplitude: 0.1
      perspective_amplitude_x: 0.1
      perspective_amplitude_y: 0.1
      patch_ratio: 0.5
      max_angle: 1.57

model:
  name: 'SuperPointNetMobileNetV2'
  eval_batch_size: 32
  detection_threshold: 0.015
  nms: 4
  top_k: 300
  dense_loss:
    enable: true
    params:
      loss_type: 'l2'
      margin: 1
      num_points: 1000
      lamda_d: 250
  detector_loss:
    enable: true
    params:
      loss_type: 'cross_entropy'
      grid_size: 8
      balance: 1.0
  subpixel:
    enable: false

train_iter: 200000
validation_interval: 2000
model_save_interval: 5000 